### ISSUE TITLE
Production Flavor Doesn't Show Users, Development Flavor Does

### ISSUE THREAD

**Issue by mowet601** [Aanu1995/Pure#11]
The Development Flavor Shows These Users.  The Production Flavor Shows No Users.  What am I missing?

![Screenshot_20211217-145211](https://user-images.githubusercontent.com/4493458/146607021-23a5bb3a-9ef4-41aa-870d-e9fcbf0bfe4b.png)
![Screenshot_20211217-144736](https://user-images.githubusercontent.com/4493458/146607023-3c05cbce-cd7c-4b05-9b48-3836f3d63617.png)

**Comment by Aanu1995** [comment]
Below is the link to clone the code for cloud functions and deploy
https://github.com/Aanu1995/Pure_Dev_Cloud_Function
